[package]
name = "dummy-esp-idf-hal"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
embedded-hal = "1"
dummy-esp-idf-sys = { path = "../dummy-esp-idf-sys" }
